export const GET_ICAO_IATA_REQUEST = 'GET_ICAO_IATA_REQUEST';
export const GET_ICAO_IATA_SUCCESS = 'GET_ICAO_IATA_SUCCESS';
export const GET_ICAO_IATA_FAIL = 'GET_ICAO_IATA_FAIL';

export const CLEAR_ICAO_IATA = 'CLEAR_ICAO_IATA';
