export const ADD_FUEL_PROVIDER_REQUEST = 'ADD_FUEL_PROVIDER_REQUEST';
export const ADD_FUEL_PROVIDER_SUCCESS = 'ADD_FUEL_PROVIDER_SUCCESS';
export const ADD_FUEL_PROVIDER_FAIL = 'ADD_FUEL_PROVIDER_FAIL';

export const UPDATE_FUEL_PROVIDER_REQUEST = 'UPDATE_FUEL_PROVIDER_REQUEST';
export const UPDATE_FUEL_PROVIDER_SUCCESS = 'UPDATE_FUEL_PROVIDER_SUCCESS';
export const UPDATE_FUEL_PROVIDER_FAIL = 'UPDATE_FUEL_PROVIDER_FAIL';
