export const ADD_FUEL_QUOTATION_REQUEST = 'ADD_FUEL_QUOTATION_REQUEST';
export const ADD_FUEL_QUOTATION_SUCCESS = 'ADD_FUEL_QUOTATION_SUCCESS';
export const ADD_FUEL_QUOTATION_FAIL = 'ADD_FUEL_QUOTATION_FAIL';

export const GET_SELECTED_FUEL_QUOTE = 'GET_SELECTED_FUEL_QUOTE';
