export const GET_ICAO_BY_COUNTRY_REQUEST = 'GET_ICAO_BY_COUNTRY_REQUEST';
export const GET_ICAO_BY_COUNTRY_SUCCESS = 'GET_ICAO_BY_COUNTRY_SUCCESS';
export const GET_ICAO_BY_COUNTRY_FAIL = 'GET_ICAO_BY_COUNTRY_FAIL';

export const GET_GROUNDHANDLER_BY_ICAO_REQUEST =
  'GET_GROUNDHANDLER_BY_ICAO_REQUEST';
export const GET_GROUNDHANDLER_BY_ICAO_SUCCESS =
  'GET_GROUNDHANDLER_BY_ICAO_SUCCESS';
export const GET_GROUNDHANDLER_BY_ICAO_FAIL = 'GET_GROUNDHANDLER_BY_ICAO_FAIL';

export const GET_GROUNDHANDLER_BY_IATA_REQUEST =
  'GET_GROUNDHANDLER_BY_IATA_REQUEST';
export const GET_GROUNDHANDLER_BY_IATA_SUCCESS =
  'GET_GROUNDHANDLER_BY_IATA_SUCCESS';
export const GET_GROUNDHANDLER_BY_IATA_FAIL = 'GET_GROUNDHANDLER_BY_IATA_FAIL';

export const GET_SELECTED_GROUNDHANDLER_BY_ICAO_OR_IATA =
  'GET_SELECTED_GROUNDHANDLER_BY_ICAO_OR_IATA';

export const GET_PREFERRED_GROUNDHANDLER_REQUEST =
  'GET_PREFERRED_GROUNDHANDLER_REQUEST';
export const GET_PREFERRED_GROUNDHANDLER_SUCCESS =
  'GET_PREFERRED_GROUNDHANDLER_SUCCESS';
export const GET_PREFERRED_GROUNDHANDLER_FAIL =
  'GET_PREFERRED_GROUNDHANDLER_FAIL';


export const UPDATE_PREFFERED_GROUND_HANDLER_REQUEST =
  'UPDATE_PREFFERED_GROUND_HANDLER_REQUEST';
export const UPDATE_PREFFERED_GROUND_HANDLER_SUCCESS =
  'UPDATE_PREFFERED_GROUND_HANDLER_SUCCESS';
export const UPDATE_PREFFERED_GROUND_HANDLER_FAIL =
  'UPDATE_PREFFERED_GROUND_HANDLER_FAIL';


export const ADD_GROUND_HANDLER_REQUEST =
  'ADD_GROUND_HANDLER_REQUEST';
export const ADD_GROUND_HANDLER_SUCCESS =
  'ADD_GROUND_HANDLER_SUCCESS';
export const ADD_GROUND_HANDLER_FAIL =
  'ADD_GROUND_HANDLER_FAIL';

export const UPDATE_GROUND_HANDLER_REQUEST =
  'UPDATE_GROUND_HANDLER_REQUEST';
export const UPDATE_GROUND_HANDLER_SUCCESS =
  'UPDATE_GROUND_HANDLER_SUCCESS';
export const UPDATE_GROUND_HANDLER_FAIL =
  'UPDATE_GROUND_HANDLER_FAIL';
