export const ADD_OPERATOR_REQUEST = 'ADD_OPERATOR_REQUEST';
export const ADD_OPERATOR_SUCCESS = 'ADD_OPERATOR_SUCCESS';
export const ADD_OPERATOR_FAIL = 'ADD_OPERATOR_FAIL';

export const UPDATE_OPERATOR_REQUEST = 'UPDATE_OPERATOR_REQUEST';
export const UPDATE_OPERATOR_SUCCESS = 'UPDATE_OPERATOR_SUCCESS';
export const UPDATE_OPERATOR_FAIL = 'UPDATE_OPERATOR_FAIL';
