export const GET_SERVICE_PROVIDER_BY_COUNTRY_REQUEST =
  'GET_SERVICE_PROVIDER_BY_COUNTRY_REQUEST';
export const GET_SERVICE_PROVIDER_BY_COUNTRY_SUCCESS =
  'GET_SERVICE_PROVIDER_BY_COUNTRY_SUCCESS';
export const GET_SERVICE_PROVIDER_BY_COUNTRY_FAIL =
  'GET_SERVICE_PROVIDER_BY_COUNTRY_FAIL';

export const ADD_SERVICE_PROVIDER_REQUEST = 'ADD_SERVICE_PROVIDER_REQUEST';
export const ADD_SERVICE_PROVIDER_SUCCESS = 'ADD_SERVICE_PROVIDER_SUCCESS';
export const ADD_SERVICE_PROVIDER_FAIL = 'ADD_SERVICE_PROVIDER_FAIL';

export const UPDATE_SERVICE_PROVIDER_REQUEST = 'UPDATE_SERVICE_PROVIDER_REQUEST';
export const UPDATE_SERVICE_PROVIDER_SUCCESS = 'UPDATE_SERVICE_PROVIDER_SUCCESS';
export const UPDATE_SERVICE_PROVIDER_FAIL = 'UPDATE_SERVICE_PROVIDER_FAIL';

export const UPDATE_PREFFERED_SERVICE_PROVIDER_REQUEST =
  'UPDATE_PREFFERED_SERVICE_PROVIDER_REQUEST';
export const UPDATE_PREFFERED_SERVICE_PROVIDER_SUCCESS =
  'UPDATE_PREFFERED_SERVICE_PROVIDER_SUCCESS';
export const UPDATE_PREFFERED_SERVICE_PROVIDER_FAIL =
  'UPDATE_PREFFERED_SERVICE_PROVIDER_FAIL';

export const GET_PREFFERED_SERVICE_PROVIDER_BY_COUNTRY_REQUEST =
  'GET_PREFFERED_SERVICE_PROVIDER_BY_COUNTRY_REQUEST';
export const GET_PREFFERED_SERVICE_PROVIDER_BY_COUNTRY_SUCCESS =
  'GET_PREFFERED_SERVICE_PROVIDER_BY_COUNTRY_SUCCESS';
export const GET_PREFFERED_SERVICE_PROVIDER_BY_COUNTRY_FAIL =
  'GET_PREFFERED_SERVICE_PROVIDER_BY_COUNTRY_FAIL';

export const GET_SELECTED_SERVICE_PROVIDER_BY_COUNTRY =
  'GET_SELECTED_SERVICE_PROVIDER_BY_COUNTRY';
