export const CREATE_SHIFT_HANDOVER_REQUEST = 'CREATE_SHIFT_HANDOVER_REQUEST';
export const CREATE_SHIFT_HANDOVER_SUCCESS = 'CREATE_SHIFT_HANDOVER_SUCCESS';
export const CREATE_SHIFT_HANDOVER_FAIL = 'CREATE_SHIFT_HANDOVER_FAIL';

export const GET_SHIFT_HANDOVER_REQUEST = 'GET_SHIFT_HANDOVER_REQUEST';
export const GET_SHIFT_HANDOVER_SUCCESS = 'GET_SHIFT_HANDOVER_SUCCESS';
export const GET_SHIFT_HANDOVER_FAIL = 'GET_SHIFT_HANDOVER_FAIL';

export const DELETE_SHIFT_HANDOVER_REQUEST = 'DELETE_SHIFT_HANDOVER_REQUEST';
export const DELETE_SHIFT_HANDOVER_SUCCESS = 'DELETE_SHIFT_HANDOVER_SUCCESS';
export const DELETE_SHIFT_HANDOVER_FAIL = 'DELETE_SHIFT_HANDOVER_FAIL';

export const UPDATE_SHIFT_HANDOVER_REQUEST = 'UPDATE_SHIFT_HANDOVER_REQUEST';
export const UPDATE_SHIFT_HANDOVER_SUCCESS = 'UPDATE_SHIFT_HANDOVER_SUCCESS';
export const UPDATE_SHIFT_HANDOVER_FAIL = 'UPDATE_SHIFT_HANDOVER_FAIL';

export const REMOVE_SHIFT_HANDOVER_FROM_STATE = 'REMOVE_SHIFT_HANDOVER_FROM_STATE';
