export const CREATE_SHIFT_REQUEST = 'CREATE_SHIFT_REQUEST';
export const CREATE_SHIFT_SUCCESS = 'CREATE_SHIFT_SUCCESS';
export const CREATE_SHIFT_FAIL = 'CREATE_SHIFT_FAIL';

export const GET_SHIFT_REQUEST = 'GET_SHIFT_REQUEST';
export const GET_SHIFT_SUCCESS = 'GET_SHIFT_SUCCESS';
export const GET_SHIFT_FAIL = 'GET_SHIFT_FAIL';

export const DELETE_SHIFT_REQUEST = 'DELETE_SHIFT_REQUEST';
export const DELETE_SHIFT_SUCCESS = 'DELETE_SHIFT_SUCCESS';
export const DELETE_SHIFT_FAIL = 'DELETE_SHIFT_FAIL';

export const UPDATE_SHIFT_REQUEST = 'UPDATE_SHIFT_REQUEST';
export const UPDATE_SHIFT_SUCCESS = 'UPDATE_SHIFT_SUCCESS';
export const UPDATE_SHIFT_FAIL = 'UPDATE_SHIFT_FAIL';

export const REMOVE_SHIFT_FROM_STATE = 'REMOVE_SHIFT_FROM_STATE';
