export const CREATE_STAFF_PROFILE_REQUEST = 'CREATE_STAFF_PROFILE_REQUEST';
export const CREATE_STAFF_PROFILE_SUCCESS = 'CREATE_STAFF_PROFILE_SUCCESS';
export const CREATE_STAFF_PROFILE_FAIL = 'CREATE_STAFF_PROFILE_FAIL';

export const GET_STAFF_PROFILE_REQUEST = 'GET_STAFF_PROFILE_REQUEST';
export const GET_STAFF_PROFILE_SUCCESS = 'GET_STAFF_PROFILE_SUCCESS';
export const GET_STAFF_PROFILE_FAIL = 'GET_STAFF_PROFILE_FAIL';

export const DELETE_STAFF_PROFILE_REQUEST = 'DELETE_STAFF_PROFILE_REQUEST';
export const DELETE_STAFF_PROFILE_SUCCESS = 'DELETE_STAFF_PROFILE_SUCCESS';
export const DELETE_STAFF_PROFILE_FAIL = 'DELETE_STAFF_PROFILE_FAIL';

export const UPDATE_STAFF_PROFILE_REQUEST = 'UPDATE_STAFF_PROFILE_REQUEST';
export const UPDATE_STAFF_PROFILE_SUCCESS = 'UPDATE_STAFF_PROFILE_SUCCESS';
export const UPDATE_STAFF_PROFILE_FAIL = 'UPDATE_STAFF_PROFILE_FAIL';

export const REMOVE_STAFF_PROFILE_FROM_STATE = 'REMOVE_STAFF_PROFILE_FROM_STATE';
