export const CREATE_TRIPSHEET_REQUEST = 'CREATE_TRIPSHEET_REQUEST';
export const CREATE_TRIPSHEET_SUCCESS = 'CREATE_TRIPSHEET_SUCCESS';
export const CREATE_TRIPSHEET_FAIL = 'CREATE_TRIPSHEET_FAIL';

export const GET_TRIPSHEET_REQUEST = 'GET_TRIPSHEET_REQUEST';
export const GET_TRIPSHEET_SUCCESS = 'GET_TRIPSHEET_SUCCESS';
export const GET_TRIPSHEET_FAIL = 'GET_TRIPSHEET_FAIL';

export const UPDATE_TRIPSHEET_REQUEST = 'UPDATE_TRIPSHEET_REQUEST';
export const UPDATE_TRIPSHEET_SUCCESS = 'UPDATE_TRIPSHEET_SUCCESS';
export const UPDATE_TRIPSHEET_FAIL = 'UPDATE_TRIPSHEET_FAIL';

export const REMOVE_TRIPSHEET_FROM_STATE = 'REMOVE_TRIPSHEET_FROM_STATE';
